### ISSUE TITLE
MX Xml Parsing taking too much time

### ISSUE THREAD

**Issue by BSethi-Fintech** [prowide/prowide-core#49] opened 2021-04-26 10:48 UTC
Hi,
We are working to parse swift MX message of type seev.031.002.09
When we are calling the below function. It is taking 300ms to 600 ms for parsing different XML messages.
**MxSeev03100209 mx = MxSeev03100209.parse(xmlMessage);**

[INFO ] 2021-04-21 21:46:01,612 Parser.mxParse() -Parsing started
[INFO ] 2021-04-21 21:46:02,010 Parser.mxParse() -Parsing end

I attached sample XML messages for which it is taking this much time. Please check why it's taking so much time as we have to process thousands of messages in a single day ad it's taking hours to process.

[MX_Sample_Xml_2.txt](https://github.com/prowide/prowide-core/files/6376434/MX_Sample_Xml_2.txt)
[MX_Sample_xml_1.txt](https://github.com/prowide/prowide-core/files/6376435/MX_Sample_xml_1.txt)

**Comment by zubri** [comment] 2021-05-29 16:39
Duplicate of https://github.com/prowide/prowide-iso20022/issues/23

**Closed by zubri** 2021-05-29 16:39 UTC
