### ISSUE TITLE
Bad performance of textTagEndBlock4 in SwiftParser

### ISSUE THREAD

**Issue by ynleborg** [prowide/prowide-core#5] opened 2017-05-23 14:18 UTC
Since version SRU2016-7.8.5 there is a performance problem in the implementation of textTagEndBlock4 in SwiftParser. Processing increased from 3 seconds to 3 minutes for 14MB file. Profiling tools show, that most time is spent in substring method. We internally reverted implementation to SRU2015-7.7 and it fixed issue.

**Comment by zubri** [comment] 2017-05-23 21:12
Hi, 

Thanks for the feedback.
We see no significant changes in the usage of substring calls in that method, neither in the whole parser.

Can you provide more details on how you are reading and parsing the 14MB file? Are you using the RJEReader?

**Comment by ynleborg** [comment] 2017-05-26 13:45
I have prepered test that reproduces the bug: https://github.com/prowide/prowide-core/pull/6

On my computer shouldParseLargeFile runs 12 seconds on SRU2016-7.8.5 and 0,187s on SRU2015-7.7

**Comment by zubri** [comment] 2017-05-30 16:52
This has been fixed to achieve previous performance. I've removed the substring call and refactored the tag start detection. It will be included in the upcoming SRU2017 release in October.

However, notice the large statement that you are using to produce the issue is not valid. And input MT940 can have at most 2K characters.

Also, the parser from 2015 7.7 you are using has a bug. It does not accept ':' as starting content in the second line of a field.

**Closed by zubri** 2017-05-30 16:52 UTC
